#include <YSI\y_hooks>

// Global interior define
#define MAPS_GSFEXTERIOR_INTERIOR      0
#define MAPS_GSFINTERIOR_INTERIOR      3

// Local drawdistance & streamdistance setting
// static Float:STREAMDISTANCE = 350.0;
// static Float:DRAWDISTANCE   = 350.0;

// GSF interior points
#define GSF_INTERIOR_GANGSHOP_POINT            2491.7261, -1701.2618, 1018.3438
// Map variables

hook OnPlayerConnect(playerid) {
    // ---
}

hook OnPlayerKeyStateChange(playerid, newkeys, oldkeys) {

    return 1;
}


